# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '684185c2-fcb2-4e62-a0ea-e3e2648eec29'
  imageRepository: 'happykafkapoc'
  containerRegistry: 'ragaetmdemo.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  tag: 'etm-kafka-streams-$(Build.BuildId)'
  REMOTE_ADDR: 'https://github.com/rajasaroj/happy-kafka-streams'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

stages:
- stage: running_git_commands
  displayName: Syncup Azure Repo with GitHub Repo
  jobs:
    - job: initiate
      displayName: initiate
      pool: 
        name: 'etm-agents-pool'
      continueOnError: false
      steps:
        - checkout: self
          clean: true
          persistCredentials: true
          displayName: run_commands
        - bash: | 
            git checkout master
            git remote add repoGithub $(REMOTE_ADDR)
            git fetch repoGithub master
            git reset --hard repoGithub/master
            git pull --rebase repoGithub master
            MY_PAT=dgmktv4fyxyivyds6dq5dtcpiv6g43owfgvkgncdpbk72vwi22gq
            B64_PAT=$(printf ":%s" "$MY_PAT" | base64)
            echo "B64 = ${B64_PAT}"
            echo "MY_PAT = ${MY_PAT}"
            git -c http.extraHeader="Authorization: Basic ${B64_PAT}" push origin master -f 



- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      # vmImage: $(vmImageName)
      name: 'etm-agents-pool'
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
